### ISSUE TITLE
Not able to run on GPU

### ISSUE THREAD

**Issue by yubailibra** [andrewcharlesjones/spatial-alignment#6]
Dear authors,
We are interested in applying your algorithm to our data. However, we encounter RuntimeErrors complaining tensors are not on the same device and thus could not run on GPU. Do you have new versions that can run on GPU? Thank you.

**Comment by andrewcharlesjones** [comment]
Thanks for noticing this. I believe I just fixed it -- I wasn't properly placing the data on the correct device when a GPU is available. Let me know if you run into issues still.

**Comment by giovp** [comment]
I just encountered the same issue on GPU:

```
2023-01-03 11:29:33 (ERROR): Failed after 0:00:09!
Traceback (most recent call last):
  File "/home/icb/giovanni.palla/miniconda3/envs/moscot/lib/python3.9/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/icb/giovanni.palla/miniconda3/envs/moscot/lib/python3.9/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/icb/giovanni.palla/miniconda3/envs/moscot/lib/python3.9/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/icb/giovanni.palla/miniconda3/envs/moscot/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/tmp/6c6ac013-509d-43e3-8cbf-fedd8186c98c/experiment.py", line 229, in train
    return experiment.train()
  File "/home/icb/giovanni.palla/miniconda3/envs/moscot/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/tmp/6c6ac013-509d-43e3-8cbf-fedd8186c98c/experiment.py", line 96, in train
    test_results = compute_gpsa(self.adata, self.kernel, self.n_epochs, self.lr)
  File "/tmp/6c6ac013-509d-43e3-8cbf-fedd8186c98c/experiment.py", line 178, in compute_gpsa
    _, G_means = train(model, model.loss_fn, optimizer)
  File "/tmp/6c6ac013-509d-43e3-8cbf-fedd8186c98c/experiment.py", line 162, in train
    G_means, G_samples, F_latent_samples, F_samples = model.forward(
  File "/home/icb/giovanni.palla/miniconda3/envs/moscot/lib/python3.9/site-packages/gpsa/models/vgpsa.py", line 269, in forward
    G_means[mod][view_idx[mod][vv]] = observed_X_spatial
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

I've installed it from pip v 0.8
